### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by defuuss** [JGeek00/adguard-home-manager#24]
Hi i cannot get access to my adguard home installed on my rpi home assistant . 
Do i need to adapt the path somewhere  ?

I uncheck the check of ssl certificat , put the internal ip with port 8123 , tried to add the path behind a0d7b954_adguard

I always get an error  , could you help me out setting this up . 

Thx

**Comment by JGeek00** [comment]
Hi. Which error are you receiving? Please do the following steps: after seeing the error, go to Settings, Advanced settings, Logs and tap on the share button. That will copy the logs into the clipboard. Then paste the logs here.

**Comment by defuuss** [comment]
I get a 404 , Status Code 
Error_code_not expected 
404:not found

When I check running on Home assistant what does it do ?

**Comment by JGeek00** [comment]
In that situation the server is not found. On the top of the new connection screen there is a representation of the connection url. Make sure that the url matches the url you use for the web admin panel.

The HA toggle has to be enabled only if your AdGuard Home is running inside Home Assistant, because the login in that situation behaves differently.

**Comment by defuuss** [comment]
Yes i saw the only thing I see is that in the url he put the port at the end [

![WhatsApp Image 2022-12-05 at 14 37 12](https://user-images.githubusercontent.com/4477023/205650825-69bd8cda-130e-41b5-aa71-0b14398c93d1.jpeg)

**Comment by JGeek00** [comment]
Probably that could be the issue. The port is not placed correctly.

**Comment by defuuss** [comment]
Ok so i need to wait for a fix ?

**Comment by JGeek00** [comment]
Yes, I have to release a fix for that.

**Comment by Greigh** [comment]
I was literally about to ask about the same thing. Good to know! Thanks :)

**Comment by Greigh** [comment]
@JGeek00 Also, I believe :8123 is a designated port for Home Assistant. Are we supposed to put in HA's port or the AdGuard Home host port we created in the Configuration of AdGuard Home in HA?

So that you're not confused, @defuuss... `/hassio/addon/a0d7b954_adguard/config` Under Network.

**Comment by JGeek00** [comment]
@defuuss for Home Assistant you have to configure a port for AdGuard Home here.
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/47545344/205784907-ef8bbf67-5ac9-42c2-8355-ca1dc7ed056c.png">

Then, on the app you have to put the IP of the HA server, that port, the credentials of your HA account and check the "Running on Home Assistant" toggle.

**Comment by JGeek00** [comment]
Fixed on v1.5.5.

**Comment by defuuss** [comment]
Ok 
I tried 2 things 

Changing the port for the webinterface adguard does not start anymore in the container of home assistant ....

With the new version url seems correct but still getting a 404

**Comment by Greigh** [comment]
> Ok I tried 2 things
> 
> Changing the port for the webinterface adguard does not start anymore in the container of home assistant ....
> 
> With the new version url seems correct but still getting a 404

Are you changing the TCP port?...

**Comment by defuuss** [comment]
Jep the web Interface port

**Comment by JGeek00** [comment]
Changing the web interface port shouldn't prevent AdGuard Home from starting. That port is only used for administration software.

**Comment by JGeek00** [comment]
Any updates on this?

**Comment by defuuss** [comment]
Sorry for the late reply , I had to change some stuff , I think there is a bug in home assistant  with the certificate , so I got it working , Thanks for the help and the client software , working great.
